API_KEY = "AIzaSyBQVw7oXrIa2d81IuGuAze56iHYVPW6ExA"
KAFKA_BROKER = "localhost:9092"
TOPIC = "youtube-data"

REGIONS = ["IN", "US", "GB", "CA", "AU"]
MAX_RESULTS = 50
PAGES_PER_REGION = 2
POLL_SECONDS = 300
REQUEST_TIMEOUT = 15
